# import os 
# import dotenv

# dotenv.load_dotenv()

# DATABASE_HOSTNAME  = os.getenv("DATABASE_HOSTNAME")
# DATABASE_USERNAME = os.getenv("DATABASE_USERNAME")
# DATABASE_PASSWORD = os.getenv("DATABASE_PASSWORD")
# DATABASE_PORT = os.getenv("DATABASE_PORT")
# DATABASE_NAME = os.getenv("DATABASE_NAME")



# SQLALCHEMY_DATABASE_URL = f"postgresql://{DATABASE_USERNAME}:{DATABASE_PASSWORD}@{DATABASE_HOSTNAME}/{DATABASE_NAME}"
# print(SQLALCHEMY_DATABASE_URL)